spring.datasource.url=jdbc:postgresql://localhost:5432/phoenix_test
spring.datasource.username=phoenix
spring.datasource.password=phoenix
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=false
spring.flyway.enabled=true
spring.flyway.clean-disabled=true
spring.jpa.show-sql=false
