spring.datasource.url=jdbc:h2:mem:phoenix;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Décommenter pour Postgres local :
# spring.datasource.url=jdbc:postgresql://localhost:5432/phoenix
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.datasource.username=phoenix
# spring.datasource.password=phoenix
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
